In [5]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df=pd.read_csv('train.csv')

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [17]:
df.dropna(axis=0,inplace=True)
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C

In [13]:
from sklearn.linear_model import LogisticRegression
logisticRegr = LogisticRegression()
A=df['Pclass']
B=df['Survived']

In [14]:
logisticRegr.fit(A,B)

ValueError: Expected 2D array, got 1D array instead:
array=[3. 1. 3. 1. 3. 3. 1. 3. 3. 2. 3. 1. 3. 3. 3. 2. 3. 2. 3. 3. 2. 2. 3. 1.
 3. 3. 3. 1. 3. 3. 1. 1. 3. 2. 1. 1. 3. 3. 3. 3. 3. 2. 3. 2. 3. 3. 3. 3.
 3. 3. 3. 3. 1. 2. 1. 1. 2. 3. 2. 3. 3. 1. 1. 3. 1. 3. 2. 3. 3. 3. 2. 3.
 2. 3. 3. 3. 3. 3. 2. 3. 3. 3. 3. 1. 2. 3. 3. 3. 1. 3. 3. 3. 1. 3. 3. 3.
 1. 1. 2. 2. 3. 3. 1. 3. 3. 3. 3. 3. 3. 3. 1. 3. 3. 3. 3. 3. 3. 2. 1. 3.
 2. 3. 2. 2. 1. 3. 3. 3. 3. 3. 3. 3. 3. 2. 2. 2. 1. 1. 3. 1. 3. 3. 3. 3.
 2. 2. 3. 3. 2. 2. 2. 1. 3. 3. 3. 1. 3. 3. 3. 3. 3. 2. 3. 3. 3. 3. 1. 3.
 1. 3. 1. 3. 3. 3. 1. 3. 3. 1. 2. 3. 3. 2. 3. 2. 3. 1. 3. 1. 3. 3. 2. 2.
 3. 2. 1. 1. 3. 3. 3. 2. 3. 3. 3. 3. 3. 3. 3. 3. 3. 1. 3. 2. 3. 2. 3. 1.
 3. 2. 1. 2. 3. 2. 3. 3. 1. 3. 2. 3. 2. 3. 1. 3. 2. 3. 2. 3. 2. 2. 2. 2.
 3. 3. 2. 3. 3. 1. 3. 2. 1. 2. 3. 3. 1. 3. 3. 3. 1. 1. 1. 2. 3. 3. 1. 1.
 3. 2. 3. 3. 1. 1. 1. 3. 2. 1. 3. 1. 3. 2. 3. 3. 3. 3. 3. 3. 1. 3. 3. 3.
 2. 3. 1. 1. 2. 3. 3. 1. 3. 1. 1. 1. 3. 3. 3. 2. 3. 1. 1. 1. 2. 1. 1. 1.
 2. 3. 2. 3. 2. 2. 1. 1. 3. 3. 2. 2. 3. 1. 3. 2. 3. 1. 3. 1. 1. 3. 1. 3.
 1. 1. 3. 1. 2. 1. 2. 2. 2. 2. 2. 3. 3. 3. 3. 1. 3. 3. 3. 3. 1. 2. 3. 3.
 3. 2. 3. 3. 3. 3. 1. 3. 3. 1. 1. 3. 3. 1. 3. 1. 3. 1. 3. 3. 1. 3. 3. 1.
 3. 2. 3. 2. 3. 2. 1. 3. 3. 1. 3. 3. 3. 2. 2. 2. 3. 3. 3. 3. 3. 2. 3. 2.
 3. 3. 3. 3. 1. 2. 3. 3. 2. 2. 2. 3. 3. 3. 3. 3. 3. 3. 2. 2. 3. 3. 1. 3.
 2. 3. 1. 1. 3. 2. 1. 2. 2. 3. 3. 2. 3. 1. 2. 1. 3. 1. 2. 3. 1. 1. 3. 3.
 1. 1. 2. 3. 1. 3. 1. 2. 3. 3. 2. 1. 3. 3. 3. 3. 2. 2. 3. 1. 2. 3. 3. 3.
 3. 2. 3. 3. 1. 3. 1. 1. 3. 3. 3. 3. 1. 1. 3. 3. 1. 3. 1. 3. 3. 3. 3. 3.
 1. 1. 2. 1. 3. 3. 3. 3. 1. 1. 3. 1. 2. 3. 2. 3. 1. 3. 3. 1. 3. 3. 2. 1.
 3. 2. 2. 3. 3. 3. 3. 2. 1. 1. 3. 1. 1. 3. 3. 2. 1. 1. 2. 2. 3. 2. 1. 2.
 3. 3. 3. 1. 1. 1. 1. 3. 3. 3. 2. 3. 3. 3. 3. 3. 3. 3. 2. 1. 1. 3. 3. 3.
 2. 1. 3. 3. 2. 1. 2. 1. 3. 1. 2. 1. 3. 3. 3. 1. 3. 3. 2. 3. 2. 3. 3. 1.
 2. 3. 1. 3. 1. 3. 3. 1. 2. 1. 3. 3. 3. 3. 3. 2. 3. 3. 2. 2. 3. 1. 3. 3.
 3. 1. 2. 1. 3. 3. 1. 3. 1. 1. 3. 2. 3. 2. 3. 3. 3. 1. 3. 3. 3. 1. 3. 1.
 3. 3. 3. 2. 3. 3. 3. 2. 3. 3. 2. 1. 1. 3. 1. 3. 3. 2. 2. 3. 3. 1. 2. 1.
 2. 2. 2. 3. 3. 3. 3. 1. 3. 1. 3. 3. 2. 2. 3. 3. 3. 1. 1. 3. 3. 3. 1. 2.
 3. 3. 1. 3. 1. 1. 3. 3. 3. 2. 2. 1. 1. 3. 1. 1. 1. 3. 2. 3. 1. 2. 3. 3.
 2. 3. 2. 2. 1. 3. 2. 3. 2. 3. 1. 3. 2. 2. 2. 3. 3. 1. 3. 3. 1. 1. 1. 3.
 3. 1. 3. 2. 1. 3. 2. 3. 3. 3. 2. 2. 3. 2. 3. 1. 3. 3. 3. 1. 3. 1. 1. 3.
 3. 3. 3. 3. 2. 3. 2. 3. 3. 3. 3. 1. 3. 1. 1. 3. 3. 3. 3. 3. 3. 1. 3. 2.
 3. 1. 3. 2. 1. 3. 3. 3. 2. 2. 1. 3. 3. 3. 1. 3. 2. 1. 3. 3. 2. 3. 3. 1.
 3. 2. 3. 3. 1. 3. 1. 3. 3. 3. 3. 2. 3. 1. 3. 2. 3. 3. 3. 1. 3. 3. 3. 1.
 3. 2. 1. 3. 3. 3. 3. 3. 2. 1. 3. 3. 3. 1. 2. 3. 1. 1. 3. 3. 3. 2. 1. 3.
 2. 2. 2. 1. 3. 3. 3. 1. 1. 3. 2. 3. 3. 3. 3. 1. 2. 3. 3. 2. 3. 3. 2. 1.
 3. 1. 3.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:
predictions = logisticRegr.predict(x_test)